apiVersion: v1
kind: Secret
metadata:
  name: {{ include "file-caching-service.fullname" . }}
  labels:
    {{- include "file-caching-service.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.secrets.r2AccessKeyId | b64enc | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.secrets.r2SecretAccessKey | b64enc | quote }}
